### ISSUE TITLE
cannot import name 'spec_augment_pytorch' from 'spec_augment'

### ISSUE THREAD

**Issue by Whisper329** [ricfrr/mpuc-mer#1]
in RAVDESS.py line 12 from spec_augment import spec_augment_pytorch it occurred an error:IMPORTERROR
cannot import name 'spec_augment_pytorch' from 'spec_augment', I tried 0.0.2 and 0.0.3 version, but I can't figure it out, can somebody help me?

**Comment by ricfrr** [comment]
Hi Whisper and thanks for your interest in this work. 

Have you tried to install the spec_augment library separately?

**Comment by SE-Nickjackson** [comment]
> 

How to install spec_augment library?

**Comment by SE-Nickjackson** [comment]
> Hi Whisper and thanks for your interest in this work.
> 
> Have you tried to install the spec_augment library separately?

> How to install spec_augment library?

**Comment by SE-Nickjackson** [comment]
> Hi Whisper and thanks for your interest in this work.
> 
> Have you tried to install the spec_augment library separately?

Anybody can tell me how to install the spec_augment library?

**Comment by SE-Nickjackson** [comment]
All right, I solved it.

**Comment by Whisper329** [comment]
thank you for replying me, i found that there was no  'spec_augment_pytorch' in 'spec_augment', but 'spec_augment_pytorch' exists in 'specAugment', so i imported 'specAugment' and i solved the problem, thank you!

**Comment by Whisper329** [comment]
> Hi Whisper and thanks for your interest in this work.
> 
> Have you tried to install the spec_augment library separately?

thank you for replying me, i found that there was no  'spec_augment_pytorch' in 'spec_augment', but 'spec_augment_pytorch' exists in 'specAugment', so i imported 'specAugment' and i solved the problem, thank you!
